imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    translator: ~
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Assetic
assetic:
    use_controller: false

# No Generate Assetic
#avanzu_admin_theme:
#    use_assetic: false

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: symfony
        connections:
            wow_auth:
                driver:   "%database_wow_auth_driver%"
                host:     "%database_wow_auth_host%"
                port:     "%database_wow_auth_port%"
                dbname:   "%database_wow_auth_name%"
                user:     "%database_wow_auth_user%"
                password: "%database_wow_auth_password%"
                charset:  UTF8
                mapping_types:
                    enum:       string
            wow_characters:
                driver:   "%database_wow_characters_driver%"
                host:     "%database_wow_characters_host%"
                port:     "%database_wow_characters_port%"
                dbname:   "%database_wow_characters_name%"
                user:     "%database_wow_characters_user%"
                password: "%database_wow_characters_password%"
                charset:  UTF8
                mapping_types:
                    enum:       string
                    bit:        integer
            wow_world:
                driver:   "%database_wow_world_driver%"
                host:     "%database_wow_world_host%"
                port:     "%database_wow_world_port%"
                dbname:   "%database_wow_world_name%"
                user:     "%database_wow_world_user%"
                password: "%database_wow_world_password%"
                charset:  UTF8
                mapping_types:
                    enum:       string
            symfony:
                driver:   "%database_symfony_driver%"
                host:     "%database_symfony_host%"
                port:     "%database_symfony_port%"
                dbname:   "%database_symfony_name%"
                user:     "%database_symfony_user%"
                password: "%database_symfony_password%"
                charset:  UTF8
                mapping_types:
                    enum:       string
        types:
            #json: Sonata\Doctrine\Types\JsonType

    orm:
        default_entity_manager: symfony
        entity_managers:
            wow_auth:
                connection: wow_auth
                mappings:
                    TCPCWDBWowAuthBundle:  ~
            wow_characters:
                connection: wow_characters
                mappings:
                    TCPCWDBWowCharactersBundle:  ~
            wow_world:
                connection: wow_world
                mappings:
                    TCPCWDBWowWorldBundle:  ~
            symfony:
                connection: symfony
                mappings:
                     AppBundle: ~
                #    DBSymfonyBundle: ~
                #    FOSUserBundle: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: asmar@sopinet.com
        sender_name: Asmar

easy_admin:
    entities:
        - AppBundle\Entity\User
        - AppBundle\Entity\SetItem