# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.userHelper:
        class: AppBundle\Services\UserHelper
        arguments: ["@fos_user.user_manager", "@security.token_storage"]
    app.customAuthenticationFailureHandler:
        class: AppBundle\Services\CustomAuthenticationFailureHandler
        arguments: ["@tcpcwdb_wow_auth.account", "@app.userHelper", "@router", "@security.token_storage"]
